### ISSUE TITLE
Utility.lua needs to be sorted and expanded

### ISSUE THREAD

**Issue by dralois** [Nostrademous/Dota2-FullOverwrite#29] opened 2017-01-16 17:02 UTC
The functions are kind of all over the place right now, I will attempt to sort them for readability.
I will add a few table functions like to check if a table contains a key and make some existing functions
available

**Comment by dralois** [comment] 2017-01-18 13:25
Done

**Comment by Nostrademous** [comment] 2017-01-18 13:27
I merged and for some reason now we are throwing errors in SortFunc comparing two nil value in GetCreepHealthDeltaPerSec()

**Comment by Nostrademous** [comment] 2017-01-18 13:33
I think I have a fix... when you reshuffled utility.lua you did this

function U.GetCreepHealthDeltaPerSec(creep)
    if U.creeps == nil then
        U.creeps = {};
    end

    if(U.creeps[creep] == nil) then
        return 0;
    else
        for _time,_health in U.PairsByKeys(U.creeps[creep],U.SortFunc()) do
            -- only Consider very recent datas
            if(GameTime() - _time < 3) then
                local e = (_health - creep:GetHealth()) / (GameTime() - _time);
                return e;
            end
        end
        return 0;
    end
end

The issue is when you pass a function as an argument you can't include the parentheses b/c then it will send the result of the function as an argument and not the actual function. So I'm changing it to be U.SortFunc from U.SortFunc()

**Comment by Nostrademous** [comment] 2017-01-18 13:34
Confirmed it works now.

**Closed by Nostrademous** 2017-01-18 13:34 UTC
